name: update_blog_posts
on:
  schedule: 
    - cron: '0 * * * *' 
jobs:
  update-readme-with-blog:
    name: update README with new blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: KruZZy/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/KruZZy"
